package com.example

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.ExtractorLinkType
import com.lagradost.cloudstream3.utils.Qualities
import com.lagradost.cloudstream3.utils.newExtractorLink

class ExampleProvider : MainAPI() {

    // Render is ONLY the text catalog now. Video bytes never touch it.
        override var mainUrl = "https://tg-cs3.onrender.com"
            override var name = "Telegram Vault"

                override val hasMainPage = true
                    override val supportedTypes = setOf(TvType.Movie)

                        // Must match StreamService.PORT in the companion app.
                            private val companionAppPort = 38471

                                private val mapper = ObjectMapper().registerKotlinModule()
                                        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

                                            data class CatalogItem(
                                                    @JsonProperty("title") val title: String = "",
                                                            @JsonProperty("parts") val parts: List<PartItem> = emptyList()
                                                                )

                                                                    data class PartItem(
                                                                            @JsonProperty("chat_id") val chatId: Long = 0,
                                                                                    @JsonProperty("message_id") val messageId: Long = 0
                                                                                        )

                                                                                            private suspend fun getCatalog(): List<CatalogItem> {
                                                                                                    return try {
                                                                                                                val text = app.get("$mainUrl/catalog").text
                                                                                                                            mapper.readValue(
                                                                                                                                            text,
                                                                                                                                                            object : TypeReference<List<CatalogItem>>() {}
                                                                                                                                                                        )
                                                                                                                                                                                } catch (e: Exception) {
                                                                                                                                                                                            emptyList()
                                                                                                                                                                                                    }
                                                                                                                                                                                                        }

                                                                                                                                                                                                            private fun PartItem.toData() = "$chatId:$messageId"

                                                                                                                                                                                                                override suspend fun getMainPage(
                                                                                                                                                                                                                        page: Int,
                                                                                                                                                                                                                                request: MainPageRequest
                                                                                                                                                                                                                                    ): HomePageResponse {
                                                                                                                                                                                                                                            val list = getCatalog().map { item ->
                                                                                                                                                                                                                                                        newMovieSearchResponse(
                                                                                                                                                                                                                                                                        item.title,
                                                                                                                                                                                                                                                                                        item.parts.first().toData(),
                                                                                                                                                                                                                                                                                                        TvType.Movie
                                                                                                                                                                                                                                                                                                                    ) { }
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                    return newHomePageResponse(
                                                                                                                                                                                                                                                                                                                                                HomePageList("Telegram Videos", list)
                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                override suspend fun search(query: String): List<SearchResponse> {
                                                                                                                                                                                                                                                                                                                                                                        return getCatalog()
                                                                                                                                                                                                                                                                                                                                                                                    .filter { it.title.contains(query, true) }
                                                                                                                                                                                                                                                                                                                                                                                                .map { item ->
                                                                                                                                                                                                                                                                                                                                                                                                                newMovieSearchResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                    item.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        item.parts.first().toData(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TvType.Movie
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) { }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                override suspend fun load(url: String): LoadResponse {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val item = getCatalog()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .firstOrNull { it.parts.first().toData() == url }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return newMovieLoadResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        item?.title ?: "Telegram Video",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    url,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TvType.Movie,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            url
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            override suspend fun loadLinks(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data: String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isCasting: Boolean,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitleCallback: (SubtitleFile) -> Unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            callback: (ExtractorLink) -> Unit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ): Boolean {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val parts = data.split(":")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (parts.size != 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val chatId = parts[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val messageId = parts[1]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            callback(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        newExtractorLink(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        source = this.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name = "Telegram Stream",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        url = "http://127.0.0.1:$companionAppPort/video?chat_id=$chatId&message_id=$messageId",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type = ExtractorLinkType.VIDEO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    referer = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    quality = Qualities.Unknown.value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }