package com.example

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.ExtractorLinkType
import com.lagradost.cloudstream3.utils.Qualities
import com.lagradost.cloudstream3.utils.newExtractorLink

class ExampleProvider : MainAPI() {

    // Must match StreamService.PORT in the companion app.
        private val companionAppPort = 38471

            // Same channel ID used by the companion app.
                private val channelId = -1004374443616L

                    override var mainUrl = "http://127.0.0.1:38471"
                        override var name = "Telegram Vault"

                            override val hasMainPage = true
                                override val supportedTypes = setOf(TvType.Movie)

                                    private val mapper = ObjectMapper()
                                            .registerKotlinModule()
                                                    .configure(
                                                                DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES,
                                                                            false
                                                                                    )

                                                                                        data class CatalogItem(
                                                                                                @JsonProperty("title")
                                                                                                        val title: String = "",

                                                                                                                @JsonProperty("parts")
                                                                                                                        val parts: List<PartItem> = emptyList()
                                                                                                                            )

                                                                                                                                data class PartItem(
                                                                                                                                        @JsonProperty("chat_id")
                                                                                                                                                val chatId: Long = 0,

                                                                                                                                                        @JsonProperty("message_id")
                                                                                                                                                                val messageId: Long = 0
                                                                                                                                                                    )

                                                                                                                                                                        private suspend fun getCatalog(): List<CatalogItem> {
                                                                                                                                                                                return try {
                                                                                                                                                                                            val text = app
                                                                                                                                                                                                            .get("$mainUrl/catalog?channel_id=$channelId")
                                                                                                                                                                                                                            .text

                                                                                                                                                                                                                                        mapper.readValue(
                                                                                                                                                                                                                                                        text,
                                                                                                                                                                                                                                                                        object : TypeReference<List<CatalogItem>>() {}
                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                            } catch (e: Exception) {
                                                                                                                                                                                                                                                                                                        emptyList()
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                        private fun PartItem.toData(): String {
                                                                                                                                                                                                                                                                                                                                return "$chatId:$messageId"
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                        override suspend fun getMainPage(
                                                                                                                                                                                                                                                                                                                                                page: Int,
                                                                                                                                                                                                                                                                                                                                                        request: MainPageRequest
                                                                                                                                                                                                                                                                                                                                                            ): HomePageResponse {

                                                                                                                                                                                                                                                                                                                                                                    val list = getCatalog()
                                                                                                                                                                                                                                                                                                                                                                                .filter { it.parts.isNotEmpty() }
                                                                                                                                                                                                                                                                                                                                                                                            .map { item ->
                                                                                                                                                                                                                                                                                                                                                                                                            newMovieSearchResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                item.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    item.parts.first().toData(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TvType.Movie
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) { }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return newHomePageResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        HomePageList(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Telegram Videos",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    override suspend fun search(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            query: String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ): List<SearchResponse> {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return getCatalog()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .filter {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    it.parts.isNotEmpty() &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        it.title.contains(query, ignoreCase = true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .map { item ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                newMovieSearchResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    item.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        item.parts.first().toData(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TvType.Movie
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) { }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                override suspend fun load(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        url: String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ): LoadResponse {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val item = getCatalog()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .firstOrNull {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                it.parts.isNotEmpty() &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    it.parts.first().toData() == url
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return newMovieLoadResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    item?.title ?: "Telegram Video",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                url,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TvType.Movie,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        url
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        override suspend fun loadLinks(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data: String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        isCasting: Boolean,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subtitleCallback: (SubtitleFile) -> Unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        callback: (ExtractorLink) -> Unit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ): Boolean {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val parts = data.split(":")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (parts.size != 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val chatId = parts[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val messageId = parts[1]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val streamUrl =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "http://127.0.0.1:$companionAppPort/video" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "?chat_id=$chatId&message_id=$messageId"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val link = newExtractorLink(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        source = this.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name = "Telegram Stream",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                url = streamUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type = ExtractorLinkType.VIDEO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                referer = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quality = Qualities.Unknown.value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            callback(link)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }